<?php

$x = 
'<div class="refinfo">
  <div style="display:table-row;">
    <div style="display:table-cell; vertical-align:top;">
      <div class="reftitle">{{title}}</div>
      <div class="refpos">Page {{chapter}}</div>
      <div><a href="{{id}}">Pleiades</a></div>
    </div>
    <div style="display:table-cell; overflow:auto;">
      <img src="http://books.google.com/books?id={{book}}&pg=PA{{gpage}}&img=1&zoom=3&hl=en&sig={{sig}}&ci=0%2C{{y1}}%2C1000%2C{{y2}}&edge=0" width="250"/>
    </div>
  </div>
  <div class="reflinks"><span class="zoomlink">Zoom in</span></div>
  </div>
  ';




$book = $this->book;


?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Narrative Map of <?php echo $book->bookTitle; ?></title>
    <script src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAA3-lTM9R7VNkgT0bRXy04ORTc7JMGZtuQ8NNgnMTM7MvoXtpKHBRXjYtpPUcaTA4JtDkxhPPn_l7vsw"
      type="text/javascript"></script>
    <script type="text/javascript" src="/scripts/timeline-2.3.0.js"></script>
    <script src="/scripts/jquery.highlight.js" type="text/javascript"></script>
    <script src="/scripts/timemap_full.pack.js" type="text/javascript"></script>
    <script src="/scripts/label_utils.js" type="text/javascript"></script>
    <script src="/scripts/herodotus.js" type="text/javascript"></script>
    <script src="/scripts/terms.js" type="text/javascript"></script>
    
    <script type="text/javascript">
        <!--
        
        <?php
        
       
        echo "var bookDataURI = '../bookdata/".urlencode($book->book).".json'; \n";
        echo "var pageDisplayURI = '../snippets/view?book=".urlencode($book->book)."&page='; \n";
    
	echo "var currentBook = '$book->book'; \n";
	echo "var currentPart = ''; \n";
	echo "var currenty1 = ''; \n";
	echo "var currenty2 = ''; \n";
    
        ?>
        
    
	
        -->
    </script>
    
	<script type="text/javascript">
	
	
	
	
// jquery is loaded in the timeline code
$(document).ready(function() {
    // set click handlers for book links
    $(".booklink").click(function() {
        var pos = $(this).text() + '.1';
        Herodotus.goToPos(pos);
    });
    // set click handlers for checkboxes
 //   $(".geotypeselector input").click(function() {
 //       var geotype = $(this).val();
 //       Herodotus.toggleGeotype(geotype);
 //   });
    // set handler for jump box
    $("#jumpbox").submit(function() {
        var pos = $("#jumpto").val(),
            patt = /^\d(\.\d{1,3})?$/;
        if (patt.test(pos)) {
            if (pos.length == 1) pos += ".1";
            Herodotus.goToPos(pos);
            // XXX: error messages here
        }
        return false;
    });
    // text links
    $("#prevlink").click(function() {
        Herodotus.goToPrevPos();
    });
    $("#nextlink").click(function() {
        Herodotus.goToNextPos();
    });
    $("#langtoggle").click(function() {
        Herodotus.toggleLang();
    });
    // initialize timemap
    Herodotus.init();
});
    </script>
    <link href="/css/basic.css" type="text/css" rel="stylesheet"/>
    <style>
    div#timelinecontainer{ height: 250px; }
    div#mapcontainer{ height: 450px; }
    </style>
  </head>

  <body onload="" onunload="GUnload();">
    <div id="help">
    <h2>Narrative Map <strong>(Alpha version!)</strong>: <em><?php echo $book->bookTitle; ?></em></h2>
    <h3><?php echo $book->bookAuthors; ?></h3>
    
 <!--   <p>Go to book:
        <span class="booklink">1</span>
        <span class="booklink">2</span>
        <span class="booklink">3</span>
        <span class="booklink">4</span>
        <span class="booklink">5</span>
        <span class="booklink">6</span>
        <span class="booklink">7</span>
        <span class="booklink">8</span>
        <span class="booklink">9</span>
        
    </p> -->
    
    <form id="jumpbox">Jump to: <input id="jumpto" name="jumpto" type="text" size="5" maxlength="5"><em id="jumphelp">E.g. "2.89"</em></form>
        
    
 <!--   <p>Show:
        <span class="geotypeselector s"><input type="checkbox" value="s" checked> Settlements</span>
        <span class="geotypeselector r"><input type="checkbox" value="r" checked> Regions</span>
        <span class="geotypeselector p"><input type="checkbox" value="p" checked> Physical features</span>
    </p> -->
    
    </div>
    <div id="sidebar">
        <div id="textwrap">
            <div id="textpane"></div>
        </div>
        <div id="textnav">
            <span id="langtoggle">Switch to Image View</span>
            <span id="prevlink" class="off">&lt;&lt; previous</span>
            <span id="nextlink">next &gt;&gt;</span>
        </div>
	<br/>
	<div style="padding:5px;background-color:#F2F2F2;">
	  <h3>Book Description</h3>
	  <p><em><?php echo $book->bookTitle; ?></em></p>
	  <p><?php echo $book->bookAuthors." (".$book->bookDate.")"; ?></p>
	  <p>Book URI: <?php echo '<a href="'.$book->bookURI.'">'.$book->bookURI.'</a>'; ?></p>
	</div>
    </div>
    <div id="timemap">
        <div id="mapcontainer">
          <div id="map"></div>
        </div>
        <div id="timelinecontainer">
          <div id="timeline"></div>
        </div>
    </div>
	
	
  </body>
</html>
