<?php

$placeIssues = $this->placeIssues;

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>GAP: Issues for <?php echo $placeIssues["place"]["title"]."(".$placeIssues["place"]["id"].")"; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/gapvis.css" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/style.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" />
		<script src="../../js/editorial/widgets.js" type="text/javascript" ></script>
      <script src="../../js/editorial/jquery.js" type="text/javascript" ></script>
		<script src="../../js/editorial/json2.js" type="text/javascript" ></script>
		<script src="../../js/editorial/utils.js" type="text/javascript" ></script>
		<script src="../../js/editorial/prototype.js" type="text/javascript" ></script>
		<script src="../../js/editorial/reportEdits.js" type="text/javascript" ></script>
	
		<style type="text/css">
			span.place {
				color:#4682b4;
				font-weight: bold;
			}
			#contentDiv {
				width:80%;
				margin-left:auto;
				margin-right:auto;
				padding-top:5%;
				padding-bottom:5%;
				margin-bottom: 10%;
			}
			#contextDiv {
				
			}
			#issuesDiv {
				
			}
			textarea.issue-note{
				width:90%;
				font-family: monospace;
			}
			#footHere {
				position: relative;
				top: 20%;
				
			}
		</style>
   </head>
    
	<body>
	
		<div id="container">
			<header>
				<h3><a href="http://gap2.alexandriaarchive.org/gapvis/index.html">GapVis</a> <span class=beta>BETA</span></h3>
				<nav> <a href="http://gap2.alexandriaarchive.org/gapvis/index.html">Home</a> &middot; <a href="http://googleancientplaces.wordpress.com/about/">About Us</a> &middot; <a href="http://googleancientplaces.wordpress.com/">Blog</a>
				</nav>
			</header>
			<div id="app-view" class="clearfix">
				
				<div id="contentDiv">
							
					<h4 style="text-align:center;">Summary Issues Reported on '<?php echo $placeIssues["place"]["title"]; ?>'</h4>
					<div id="contextDiv">
						<h5>Context Information</h5>
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<tbody>
								<tr>
									<th>Document Title</th><td><?php echo $placeIssues["document"]["title"]; ?></td>
								</tr>
								<tr>
									<th>Document Source</th><td><a href="<?php echo $placeIssues["document"]["url"]; ?>" target="_blank"><?php echo $placeIssues["document"]["url"]; ?></a></td>
								</tr>
								<tr>
									<th>GapVis Summary</th><td><a href="<?php echo "../../gapvis/index.html#book/".$placeIssues["docID"]."/place/".$placeIssues["place"]["id"]; ?>" target="_blank">View this place in GapVis</a></td>
								</tr>
								<tr>
									<th>Place Name</th><td><?php echo $placeIssues["place"]["title"]; ?></td>
								</tr>	
								<tr>
									<th>Place URI</th>
									<td><a href="<?php echo $placeIssues["place"]["uri"]; ?>" target="_blank"><?php echo $placeIssues["place"]["uri"]; ?></a><br/>
										<form style="background-color:#F0F0F0; padding-top:2%;" class="form-horizontal" method="post" action="../../report/change-place-uri">
											<input type="hidden" name="uriID" value="<?php echo $placeIssues["place"]["id"]; ?>" />
											<div class="control-group">
												<label class="control-label" for="newURI">Change URI</label>
												<input id="newURI" style="margin-left:5px; width:50%;" type="text" name="newURI" value="<?php echo $placeIssues["place"]["uri"]; ?>" /><br/>
											</div>
											<div class="control-group">
												<label class="control-label" for="URIsub">Update URI</label>
												<button style="margin-left:5px;" id="URIsub" class="btn btn-warning btn-mini" title="Update this URI" type="submit">Update</button>
											</div>
											<?php
											if(is_array($this->uriErrors)){
											?>
												<div style="padding:5px;">
													<h6>Errors in updating URI</h6>
													<ul>
												
												<?php
													foreach($this->uriErrors as $error){
														echo "<li>$error</li>";
													}
												?>
													</ul>
												</div>
											<?php
											}//end case with URI errors
											?>
										</form>
									</td>
								</tr>	
								<tr>
									<th>Latitude</th><td><?php echo $placeIssues["place"]["ll"][0]; ?></td>
								</tr>
								<tr>
									<th>Longitude</th><td><?php echo $placeIssues["place"]["ll"][1]; ?></td>
								</tr>
								<?php
								if(stristr($placeIssues["place"]["uri"],"http://pleiades.stoa.org")){
								?>
								
								<tr>
									<th>Synch with Pleiades</th>
									<td>
										<form style="background-color:#F0F0F0; padding-top:2%;" class="form-horizontal" method="post" action="../../report/api-pleiades-update">
											<input type="hidden" name="uriID" value="<?php echo $placeIssues["place"]["id"]; ?>" />
											<input type="hidden" name="uri" value="<?php echo $placeIssues["place"]["uri"]; ?>" />
											<p>Get latest place name and coordinate information from Pleiades:</p>
											<button style="margin-left:5px;" id="URIup" class="btn btn-warning btn-mini" title="Update this URI" type="submit">Update</button>
											
										</form>
									</td>
								</tr>
								
								<?php
								}//end case with pleiades data
								?>
								
							</tbody>
						</table>
					</div>
						
					<div id="issuesDiv">
						<h5>Issues</h5>
					<?php
					if(is_array($placeIssues["issues"])){
							
					?>
					
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<thead>
								<tr>
									<th>Delete</th>
									<!-- <th>Issue ID</th> -->
									<th>Time</th>
									<th>Issue</th>
								</tr>
							</thead>
							<tbody>
							<?php
							foreach($placeIssues["issues"] as $issue){
							?>
								<tr id="issue-<?php echo $issue["id"]; ?>">
									<td><form method="post" action="../../report/delete-issue">
											<input type="hidden" value="<?php echo $issue["id"]; ?>" name="issueID" />
											<input type="hidden" value="<?php echo $issue["tokenID"]; ?>" name="tokenID" />
											<button class="btn btn-warning btn-mini" title="Delete this issue" type="submit">X</button>
										</form>
									</td>
									<!-- <td><?php echo $issue["id"]; ?></td> -->
									<td><?php echo $issue["updated"]; ?></td>
									<td>
										<form method="post" action="../../report/update-issue">
											<input type="hidden" value="<?php echo $issue["id"]; ?>" name="issueID" />
											<input type="hidden" value="<?php echo $issue["tokenID"]; ?>" name="tokenID" />
											<textarea name="newNote" class="issue-note" id="issue-note-<?php echo $issue["id"]; ?>" rows="4"><?php echo $issue["note"]; ?></textarea>
											<br/>
											<div id="up-mess-<?php echo $issue["id"]; ?>"></div>
											<button class="btn btn-inverse btn-mini" title="Delete this issue" type="submit">Update</button>
										</form>
									</td>
								</tr>
							<?php	
							}//end loop through issues
							
							?>
							</tbody>
						</table>
						
				<?php
					}//end case with issues
					else{
						echo "<p>No issues reported on this specific token (on this page).</p>";
					}
				?>
					</div>
				
				</div>
				
				<footer id="footHere"> GapVis (c) 2011-2013 <a href="http://www.nickrabinowitz.com">Nick Rabinowitz</a> / <a href="http://googleancientplaces.wordpress.com/">Google Ancient Places</a>. Hosting by <a href="http://alexandriaarchive.org/">AlexandriaArchive.org</a>. Funding by&nbsp;&nbsp;<img src="../../gapvis/images/google_logo.png" alt=Google>.
					</footer>
				
			</div>
			
		</div>
	
	</body>
</html>
