<?php

$tokenIssues = $this->tokenIssues;
$requestParams = $this->requestParams;
$docID = $this->docID;
unset($requestParams["controller"]);
unset($requestParams["action"]);
unset($requestParams["module"]);

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>GAP: Issues for <?php echo $tokenIssues["token"]."(".$tokenIssues["tokenID"].")"; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/gapvis.css" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/style.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" />
		<script src="../../js/editorial/widgets.js" type="text/javascript" ></script>
      <script src="../../js/editorial/jquery.js" type="text/javascript" ></script>
		<script src="../../js/editorial/json2.js" type="text/javascript" ></script>
		<script src="../../js/editorial/utils.js" type="text/javascript" ></script>
		<script src="../../js/editorial/prototype.js" type="text/javascript" ></script>
		<script src="../../js/editorial/reportEdits.js" type="text/javascript" ></script>
		<script src="http://opencontext.org/js/jquery/jquery-1.7.2.min.js" type="text/javascript"></script>
		<script src="http://opencontext.org/js/bootstrap/bootstrap-transition.js" type="text/javascript"></script>
		<script src="http://opencontext.org/js/bootstrap/bootstrap-tab.js" type="text/javascript"></script>
		<script src="http://opencontext.org/js/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script>
	 	<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
		<script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
		<script src="http://maps.google.com/maps/api/js?v=3.2&sensor=false"></script>
		<script src="http://opencontext.org/js/map-browse/GoogleLayers.js" type="text/javascript"></script>

	
	
		<style type="text/css">
			span.place {
				color:#4682b4;
				font-weight: bold;
			}
			#contentDiv {
				width:80%;
				margin-left:auto;
				margin-right:auto;
				padding-top:5%;
				padding-bottom:5%;
				margin-bottom: 10%;
			}
			#contextDiv {
				
			}
			#issuesDiv {
				
			}
			textarea.issue-note{
				width:90%;
				font-family: monospace;
			}
			#footHere {
				position: relative;
				top: 20%;
				
			}
			span.highlight {
				font-weight: bold;
				color: #428bca;
				background-color:yellow;
			}
			div.tab {
				display: table;
			}
			div.tr {
				display: table-row;
			}
			div.td {
				display: table-cell;
				padding: 2%;
				vertical-align: middle;
			}
			div.tdtight {
				display: table-cell;
				padding: 2px;
				vertical-align: middle;
			}
		</style>
   </head>
    
	<body>
	
		<div id="container">
			<header style="padding-bottom:5%;">
				<h3><a href="http://gap2.alexandriaarchive.org/gapvis/index.html">GapVis</a> <span class=beta>BETA</span></h3>
				<div class="tab" style="width:100%;">
					<div class="tr">
						<div class="td" style="width:30%;">
				<nav> <a href="http://gap2.alexandriaarchive.org/gapvis/index.html">Home</a> &middot; <a href="http://googleancientplaces.wordpress.com/about/">About Us</a> &middot; <a href="http://googleancientplaces.wordpress.com/">Blog</a>
				
				</nav>
						</div>
						<div class="td" style="width:30%;">
							<div class="tab" style="width:100%;">
								<form action="../../report/search" method="get">
									<input name="docID" type="hidden" value="<?php echo $this->docID; ?>" />
									<div class="tr">
										<div class="tdtight">
											<label for="tokenSearch" class="col-sm-2 control-label">Token Search</label>
										</div>
										<div class="tdtight">
											<input name="q" type="search" class="form-control" id="tokenSearch" placeholder="Search term" />
										</div>
									</div>
									<div class="tr">
										<div class="tdtight">
											 
										</div>
										<div class="tdtight">
											<button type="submit" class="btn btn-default btn-sm">Search</button>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="td" style="width:30%;">
							<div class="tab" style="width:100%;">
								<form action="../../report/search" method="get">
									<input name="docID" type="hidden" value="<?php echo $this->docID; ?>" />
									<div class="tr">
										<div class="tdtight">
											<label for="uriSearch" class="col-sm-2 control-label">Place URI Search</label>
										</div>
										<div class="tdtight">
											<input name="uri" type="search" class="form-control" id="uriSearch" placeholder="Search Place URI" />
										</div>
									</div>
									<div class="tr">
										<div class="tdtight">
											 
										</div>
										<div class="tdtight">
											<button type="submit" class="btn btn-default btn-sm">Search</button>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</header>
			<div id="app-view" class="clearfix">
				
				<div id="contentDiv">
							
					<h3 style="text-align:center;">Search Results for '<?php echo $this->searchTerm; ?>' [<?php echo $this->searchType; ?>]</h3>
					<div id="contextDiv">
						<?php
						
						if(is_array($this->foundTokens)){
							$foundTokens = $this->foundTokens;
							
						?>
						<h5>Token Search Results (<?php echo $foundTokens["count"]; ?> total)
						<?php
							if($foundTokens["prevPage"]){
								$newParams = $requestParams;
								$newParams["page"] = $foundTokens["prevPage"];
								$url = "../../report/search?".http_build_query($newParams);
								echo " <a href=\"".$url."\">Previous</a>";
							}
							if($foundTokens["nextPage"]){
								$newParams = $requestParams;
								$newParams["page"] = $foundTokens["nextPage"];
								$url = "../../report/search?".http_build_query($newParams);
								echo " <a href=\"".$url."\">Next</a>";
							}
							
						?>
						
						</h5>
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<thead>
								<th>Link to Token</th>
								<th>Context</th>
							</thead>
							<tbody>
								<?php
								foreach($foundTokens["tokens"] AS $tokenItem){
								?>
								
								<tr>
									<td><a href="../../report/token-issues/<?php echo $tokenItem["id"]; ?>"><?php echo $tokenItem["id"]; ?></a></td>
									<td><?php echo $tokenItem["context"]; ?></td>
								</tr>
									
									
								<?php	
								}
								?>
							</tbody>
						</table>
						<?php
						
						//echo print_r($requestParams);
						
						}
						
						if(is_array($this->relatedPlaceTokens)){
							$relatedPlaceTokens = $this->relatedPlaceTokens;
						?>
						<h5>Place URI Search Results</h5>
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<tbody>
								<tr>
									<th>Place Name</th><td id="geo-label"><?php echo $relatedPlaceTokens[0]["label"]; ?></td>
								</tr>	
								<tr>
									<th>Place URI</th><td id="geo-source"><a href="<?php echo $relatedPlaceTokens[0]["uri"]; ?>" target="_blank"><?php echo $relatedPlaceTokens[0]["uri"]; ?></a></td>
								</tr>	
								<tr>
									<th>Latitude</th><td id="geo-lat"><?php echo $relatedPlaceTokens[0]["latitude"]; ?></td>
								</tr>
								<tr>
									<th>Longitude</th><td id="geo-lon"><?php echo $relatedPlaceTokens[0]["longitude"]; ?></td>
								</tr>
								<tr>
									<th>Map</th><td><div id="map" style="height:200px;"></div></td>
								</tr>
								<tr>
									<th>Update via Pleaides API
									</th>
									<td><form action="../../report/api-pleiades-update" method="post">
										<input name="uri" value="<?php echo $relatedPlaceTokens[0]["uri"]; ?>" type="hidden" />
										<button type="submit" class="btn btn-default btn-sm">API update</button>
									</form>
									<br/>
									<p class=""><small><em>Fetches current place data directly from Pleiades. Updates location and name.</em></small></p>
									</td>
								</tr>
								<tr>
									<th>Tokens Sharing this Place Reference</th><td><?php
									
									$relPlTokOutput = false;
									foreach($relatedPlaceTokens as $tokenArray){
										$id = $tokenArray["id"];
										$placeToken = $tokenArray["token"];
										$actLink = "<a href=\"../../report/token-issues/$id\">$placeToken</a>";
										if(!$relPlTokOutput){
											$relPlTokOutput = $actLink;
										}
										else{
											$relPlTokOutput .= ", ".$actLink;
										}
									}
									echo $relPlTokOutput;
									?></td>
								</tr>
								
								<?php
								if(is_array($this->placeURIs)){
								?>
								
								<tr>
									<th>Other Place URIs in Use</th><td><?php
									
									$relPlTokOutput = false;
									foreach($this->placeURIs as $placeArray){
										$uri = $placeArray["uri"];
										$placeLabel = $placeArray["label"];
										$actLink = "<a href=\"../../report/search/?uri=".urlencode($uri)."\">$placeLabel</a>";
										if(!$relPlTokOutput){
											$relPlTokOutput = $actLink;
										}
										else{
											$relPlTokOutput .= ", ".$actLink;
										}
									}
									echo $relPlTokOutput;
									?></td>
								</tr>	
								<?php
								
								}//end case with place URIs
								
								?>
							</tbody>
						</table>
						<?php	
						}
						?>
						
					</div>
				</div>
			</div>
		</div>
		
		
		
		<script type="text/javascript">
				var actLatDom = document.getElementById("geo-lat");
				var actLonDom = document.getElementById("geo-lon");
				var actGeoLabelDom = document.getElementById("geo-label");
				var actLat = actLatDom.innerHTML;
				var actLon = actLonDom.innerHTML;
				var actGeoLabel = actGeoLabelDom.innerHTML;
				var popUpMessage = "<div><p class=\"tinyText\">[Lat: "+ actLat + ", Lon: " + actLon  +"] " + actGeoLabel + "</p></div>";
		  
		  
				var satelliteView = 1;
				var map = L.map('map').setView([actLat, actLon], 6);
				var bounds = new L.LatLngBounds();
				var osmTiles = L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
            });
            
            var mapboxTiles = L.tileLayer('http://api.tiles.mapbox.com/v3/ekansa.map-tba42j14/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://MapBox.com">MapBox.com</a> '
            });
            
            var ESRISatelliteTiles = L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}', {
                attribution: '&copy; <a href="http://services.arcgisonline.com/">ESRI.com</a> '
            });
            
            var gmapRoad = new L.Google('ROADMAP');
            var gmapSat = new L.Google('SATELLITE');
            var gmapTer = new L.Google('TERRAIN');
            
            var baseMaps = {
                "Google-Terrain": gmapTer,
                "Google-Satellite": gmapSat,
                "ESRI-Satellite": ESRISatelliteTiles,
                "Google-Roads": gmapRoad,
                "OpenStreetMap": osmTiles,
                "MapBox": mapboxTiles,
            };
           
            if(satelliteView){
                map.addLayer(gmapSat);
            }
            else{
                map.addLayer(gmapTer);
            }
            map._layersMaxZoom = 20;
            L.control.layers(baseMaps).addTo(map);
				
				
				var popup = L.popup()
					 .setContent(popUpMessage);
				
				var marker = L.marker([actLat, actLon]).addTo(map).bindPopup(popup);

				
		  </script>
		
		
		
		
	</body>
</html>
