<?php

$tokenIssues = $this->tokenIssues;

?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>GAP: Issues for <?php echo $tokenIssues["token"]."(".$tokenIssues["tokenID"].")"; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/gapvis.css" />
		<link rel="stylesheet" type="text/css" href="../../gapvis/css/style.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap.css" />
		<link rel="stylesheet" type="text/css" href="http://getbootstrap.com/2.3.2/assets/css/bootstrap-responsive.css" />
		<script src="../../js/editorial/widgets.js" type="text/javascript" ></script>
      <script src="../../js/editorial/jquery.js" type="text/javascript" ></script>
		<script src="../../js/editorial/json2.js" type="text/javascript" ></script>
		<script src="../../js/editorial/utils.js" type="text/javascript" ></script>
		<script src="../../js/editorial/prototype.js" type="text/javascript" ></script>
		<script src="../../js/editorial/reportEdits.js" type="text/javascript" ></script>
	
		<style type="text/css">
			span.place {
				color:#4682b4;
				font-weight: bold;
			}
			#contentDiv {
				width:80%;
				margin-left:auto;
				margin-right:auto;
				padding-top:5%;
				padding-bottom:5%;
				margin-bottom: 10%;
			}
			#contextDiv {
				
			}
			#issuesDiv {
				
			}
			textarea.issue-note{
				width:90%;
				font-family: monospace;
			}
			#footHere {
				position: relative;
				top: 20%;
				
			}
		</style>
   </head>
    
	<body>
	
		<div id="container">
			<header>
				<h3><a href="http://gap2.alexandriaarchive.org/gapvis/index.html">GapVis</a> <span class=beta>BETA</span></h3>
				<nav> <a href="http://gap2.alexandriaarchive.org/gapvis/index.html">Home</a> &middot; <a href="http://googleancientplaces.wordpress.com/about/">About Us</a> &middot; <a href="http://googleancientplaces.wordpress.com/">Blog</a>
				</nav>
			</header>
			<div id="app-view" class="clearfix">
				
				<div id="contentDiv">
							
					<h4 style="text-align:center;">Summary Issues Reported on '<?php echo $tokenIssues["token"]; ?>'</h4>
					<div id="contextDiv">
						<h5>Context Information</h5>
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<tbody>
								<tr>
									<th>Document Title</th><td><?php echo $tokenIssues["document"]["title"]; ?></td>
								</tr>
								<tr>
									<th>Source URI</th><td><a href="<?php echo $tokenIssues["document"]["url"]; ?>" target="_blank"><?php echo $tokenIssues["document"]["url"]; ?></a></td>
								</tr>
								<tr>
									<th>Page</th><td><?php echo $tokenIssues["pageID"]; ?> <a href="../../gapvis/index.html#book/<?php echo $tokenIssues["docID"]; ?>/read/<?php echo $tokenIssues["pageID"]; ?>">[View page on GapVis]</a></td>
								</tr>
								<tr>
									<th>Context</th><td><?php echo $tokenIssues["context"]; ?></td>
								</tr>
								<?php
								if(is_array($tokenIssues["place"])){
								?>
								<form method="post" action="../../report/update-geo" >
								<tr>
									<th>Place Name</th><td><?php echo $tokenIssues["place"]["label"]; ?></td>
								</tr>	
								<tr>
									<th>Place URI</th><td><a href="<?php echo $tokenIssues["place"]["uri"]; ?>" target="_blank"><?php echo $tokenIssues["place"]["uri"]; ?></a></td>
								</tr>	
								<tr>
									<th>Latitude</th><td><?php echo $tokenIssues["place"]["latitude"]; ?></td>
								</tr>
								<tr>
									<th>Longitude</th><td><?php echo $tokenIssues["place"]["longitude"]; ?></td>
								</tr>
								</form>
								<?php	
								}//end case with place data
								?>
							</tbody>
						</table>
					</div>
						
					<div id="issuesDiv">
						<h5>Issues</h5>
					<?php
					if(is_array($tokenIssues["issues"])){
							
					?>
					
						<table class="table table-striped table-condensed table-hover table-bordered data-tab">
							<thead>
								<tr>
									<th>Delete</th>
									<!-- <th>Issue ID</th> -->
									<th>Time</th>
									<th>Issue</th>
								</tr>
							</thead>
							<tbody>
							<?php
							foreach($tokenIssues["issues"] as $issue){
							?>
								<tr id="issue-<?php echo $issue["id"]; ?>">
									<td><form method="post" action="../../report/delete-issue">
											<input type="hidden" value="<?php echo $issue["id"]; ?>" name="issueID" />
											<input type="hidden" value="<?php echo $issue["tokenID"]; ?>" name="tokenID" />
											<button class="btn btn-warning btn-mini" title="Delete this issue" type="submit">X</button>
										</form>
									</td>
									<!-- <td><?php echo $issue["id"]; ?></td> -->
									<td><?php echo $issue["updated"]; ?></td>
									<td>
										<form method="post" action="../../report/update-issue">
											<input type="hidden" value="<?php echo $issue["id"]; ?>" name="issueID" />
											<input type="hidden" value="<?php echo $issue["tokenID"]; ?>" name="tokenID" />
											<textarea name="newNote" class="issue-note" id="issue-note-<?php echo $issue["id"]; ?>" rows="4"><?php echo $issue["note"]; ?></textarea>
											<br/>
											<div id="up-mess-<?php echo $issue["id"]; ?>"></div>
											<button class="btn btn-inverse btn-mini" title="Delete this issue" type="submit">Update</button>
										</form>
									</td>
								</tr>
							<?php	
							}//end loop through issues
							
							?>
							</tbody>
						</table>
						
				<?php
					}//end case with issues
					else{
						echo "<p>No issues reported on this specific token (on this page).</p>";
					}
				?>
					</div>
				
				</div>
				
				<footer id="footHere"> GapVis (c) 2011-2013 <a href="http://www.nickrabinowitz.com">Nick Rabinowitz</a> / <a href="http://googleancientplaces.wordpress.com/">Google Ancient Places</a>. Hosting by <a href="http://alexandriaarchive.org/">AlexandriaArchive.org</a>. Funding by&nbsp;&nbsp;<img src="../../gapvis/images/google_logo.png" alt=Google>.
					</footer>
				
			</div>
			
		</div>
	
	</body>
</html>
